apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      
      containers:
      - name: nexus
        image: gcr.io/abdelrahman-377520/nexus-img:1
        ports:
        - containerPort: 8081
      

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nexus